### ISSUE TITLE
Set up the kanban board for the capstone project

### ISSUE THREAD

**Issue by tajemouti** [tajemouti/js-capstone-project#21]
Hi reviewer,

- This is the [link](https://github.com/tajemouti/js-capstone-project/projects/3) to the kanban board project.
- Our team is just two partners.

**Comment by taldr27** [comment]
# Status: Required Changes ♻️♻️
Hello @tajemouti, @BilalLiaquat7, 

Good job so far! 
You're making good progress on the project, but some issues still need to be addressed before you can move on to the next stage. Keep up the good work! 💪

![almost-there](https://media.giphy.com/media/l1JojjVanlckKIHMQ/giphy.gif)

## Highlights 🎉
✅ Good job with your Kanban board setup.

## Required Changes ♻️
_Check the comments under the review._

- [ ] Kindly ensure all your tasks are assigned according to Students A and B. The group tasks can have multiple assignees.
![image](https://github.com/tajemouti/js-capstone-project/assets/107952724/92fd0220-47a3-42bf-be63-9a859a859b53)

------
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @taldr27 in your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

**Comment by AbelG101** [comment]
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @tajemouti & @BilalLiaquat7 👋, 

**Your Kanban board is complete!  There is nothing else to say other than... it's time to start coding.
Congratulations! 🎉 🥳🥇**

## Highlights
- Proper Kanban template is used ✔
- Each team member is assigned a card✔
- All cards are distributed fairly ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
